#!/usr/bin/env bash
# One-click deploy for Debian/Ubuntu/RHEL/Fedora. Run as root.
#
# Usage:
#   # Remote one-liner (recommended):
#   curl -sSL https://raw.githubusercontent.com/Knaithe/1DayNews/master/deploy.sh | sudo bash
#
#   # With config via env (non-interactive, for CI/cloud-init):
#   curl -sSL ... | sudo TG_BOT_TOKEN=xxx TG_CHAT_ID=yyy GH_TOKEN=zzz bash
#
#   # From a local checkout:
#   sudo bash deploy.sh
#
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/Knaithe/1DayNews.git}"
APP_DIR="${APP_DIR:-/opt/vuln-monitor}"
APP_USER="${APP_USER:-vuln}"
SYSTEMD_DIR=/etc/systemd/system

# ---------- 0. root check ----------
if [ "$EUID" -ne 0 ]; then
    echo "run as root (sudo bash deploy.sh)" >&2
    exit 1
fi

# ---------- 1. distro deps ----------
echo ">>> [1/7] installing base packages..."
if command -v apt-get >/dev/null 2>&1; then
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq
    apt-get install -qq -y python3 python3-venv python3-pip git curl ca-certificates
elif command -v dnf >/dev/null 2>&1; then
    dnf install -y -q python3 python3-pip git curl ca-certificates
elif command -v yum >/dev/null 2>&1; then
    yum install -y -q python3 python3-pip git curl ca-certificates
else
    echo "unsupported distro (need apt-get / dnf / yum)" >&2
    exit 1
fi

# ---------- 2. fetch / update source ----------
echo ">>> [2/7] syncing source to $APP_DIR ..."
SELF_DIR="$(cd "$(dirname "$(readlink -f "$0" 2>/dev/null || echo "$0")")" 2>/dev/null && pwd || echo "")"

if [ -d "$APP_DIR/.git" ]; then
    git -C "$APP_DIR" pull --ff-only
elif [ -n "$SELF_DIR" ] && [ -f "$SELF_DIR/vuln_monitor.py" ]; then
    # running from a local checkout — copy files in
    mkdir -p "$APP_DIR"
    for f in vuln_monitor.py requirements.txt env.example probe_feeds.py \
             vuln-monitor.service vuln-monitor.timer deploy.sh README.md; do
        [ -f "$SELF_DIR/$f" ] && install -m 644 "$SELF_DIR/$f" "$APP_DIR/$f"
    done
else
    # fresh install via curl|bash — clone the repo
    git clone --depth=1 "$REPO_URL" "$APP_DIR"
fi

# ---------- 3. system user ----------
echo ">>> [3/7] ensuring system user '$APP_USER' ..."
id "$APP_USER" &>/dev/null || \
    useradd --system --home-dir "$APP_DIR" --shell /usr/sbin/nologin "$APP_USER"

# ---------- 4. .env (env vars > interactive > reuse existing) ----------
echo ">>> [4/7] configuring .env ..."
if [ -f "$APP_DIR/.env" ] && [ -z "${FORCE_ENV:-}" ]; then
    echo "    reusing existing $APP_DIR/.env (set FORCE_ENV=1 to overwrite)"
else
    # prompt only if we have a TTY and the var isn't in env
    if [ -z "${TG_BOT_TOKEN:-}" ]; then
        if [ -t 0 ] || [ -r /dev/tty ]; then
            read -rp "  Telegram Bot Token (from @BotFather): " TG_BOT_TOKEN </dev/tty
        else
            echo "ERROR: TG_BOT_TOKEN not set and no TTY available." >&2
            echo "       Pass via env: sudo TG_BOT_TOKEN=... TG_CHAT_ID=... bash deploy.sh" >&2
            exit 1
        fi
    fi
    if [ -z "${TG_CHAT_ID:-}" ]; then
        if [ -t 0 ] || [ -r /dev/tty ]; then
            read -rp "  Telegram Chat/Channel ID (e.g. -1001234567890): " TG_CHAT_ID </dev/tty
        else
            echo "ERROR: TG_CHAT_ID not set." >&2
            exit 1
        fi
    fi
    if [ -z "${GH_TOKEN:-}" ] && { [ -t 0 ] || [ -r /dev/tty ]; }; then
        read -rp "  GitHub PAT (optional, Enter to skip): " GH_TOKEN </dev/tty || true
    fi

    umask 077
    cat > "$APP_DIR/.env" <<EOF
# generated by deploy.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
TG_BOT_TOKEN=${TG_BOT_TOKEN}
TG_CHAT_ID=${TG_CHAT_ID}
GH_TOKEN=${GH_TOKEN:-}
# HTTPS_PROXY=
EOF
    chmod 600 "$APP_DIR/.env"
fi

# ---------- 5. venv + deps ----------
echo ">>> [5/7] setting up venv + deps ..."
if [ ! -d "$APP_DIR/venv" ]; then
    python3 -m venv "$APP_DIR/venv"
fi
"$APP_DIR/venv/bin/pip" install --quiet --upgrade pip
"$APP_DIR/venv/bin/pip" install --quiet -r "$APP_DIR/requirements.txt"

chown -R "$APP_USER:$APP_USER" "$APP_DIR"
chmod 600 "$APP_DIR/.env"

# ---------- 6. systemd units ----------
echo ">>> [6/7] installing systemd units ..."
install -m 644 "$APP_DIR/vuln-monitor.service" "$SYSTEMD_DIR/vuln-monitor.service"
install -m 644 "$APP_DIR/vuln-monitor.timer"   "$SYSTEMD_DIR/vuln-monitor.timer"
systemctl daemon-reload

# ---------- 7. warm cache (dry) then enable timer ----------
echo ">>> [7/7] warming cache (dry run, NO Telegram push) ..."
# env -i guarantees no TG_* leak from the installer shell — forces dry mode
sudo -u "$APP_USER" env -i \
    HOME="$APP_DIR" \
    PATH="/usr/bin:/bin" \
    "$APP_DIR/venv/bin/python" "$APP_DIR/vuln_monitor.py" || {
        echo "    (cache warm exited non-zero; it's OK, timer will retry)"
    }

systemctl enable --now vuln-monitor.timer

echo
echo "============================================================"
echo "  deployed."
echo "  status:     systemctl status vuln-monitor.timer"
echo "  next fire:  systemctl list-timers vuln-monitor.timer"
echo "  live logs:  journalctl -u vuln-monitor.service -f"
echo "  file logs:  tail -f $APP_DIR/vuln_monitor.log"
echo "  run now:    sudo systemctl start vuln-monitor.service"
echo "============================================================"
